[package]
name = "pidtree_mon"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39", features = ["full"] }
log = "0.4"
env_logger = "0.11"
procfs = "0.16"
fork = "0.2"
daemonize = "0.5"
num = "0.4"
num-derive = "0.4"
num-traits = "0.2"
futures = "0.3"
itertools = "0.13"
