[package]
name = "fire"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39", features = ["full"] }
log = "0.4"
env_logger = "0.11"
procfs = "0.16"
fork = "0.2"
daemonize = "0.5"
